<?php
include('enquiry.php');
include('header1.php');
include('indexPages/event_award.php');
include('indexPages/about.php');
include('indexPages/aboutCity.php');
include('indexPages/aboutGallery.php');
include('topFooter.php');
include('bottomFooter.php');
?>